{% set version = '0.4.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hms
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hms_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hms/hms_{{ version }}.tar.gz
  sha256: a57820b3e3221e973cba9500b4ad7953730110ee398693d150af833f26d5d0bc

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: crayon, lubridate, pillar (>= 1.1.0), testthat
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-pkgconfig
    - r-rlang

  run:
    - r-base
    - r-pkgconfig
    - r-rlang

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('hms')"           # [not win]
    - "\"%R%\" -e \"library('hms')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/tidyverse/hms
  license: GPL-3
  summary: Implements an S3 class for storing and formatting time-of-day values, based on the
    'difftime' class.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: hms
# Title: Pretty Time of Day
# Date: 2018-03-10
# Version: 0.4.2
# Authors@R: c( person("Kirill", "Muller", role = c("aut", "cre"), email = "krlmlr+r@mailbox.org"), person("The R Consortium", role = "fnd") )
# Description: Implements an S3 class for storing and formatting time-of-day values, based on the 'difftime' class.
# Imports: methods, pkgconfig, rlang
# Suggests: crayon, lubridate, pillar (>= 1.1.0), testthat
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/tidyverse/hms
# BugReports: https://github.com/tidyverse/hms/issues
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2018-03-10 15:21:11 UTC; muelleki
# Author: Kirill Muller [aut, cre], The R Consortium [fnd]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2018-03-10 21:33:37 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
