# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "skgmM8TlnQmYDBqv122Dn3AB3zFfRQWL1l0DzCgB3vcOawLNtohvSye6PwmbSqU/1I0nP9KrlgAyUvloKBiogYFIb9g6jaErAJtqYwq7fkcG4kOD0TtpMI5BbsnikTSYcIBgAmMhYPo2pOpzVhRx5Vr3+sYuMHiDHunsfqMV2HOdaotaNX3c9Lh8Vn5KNXaAlm+GU0N/t+fxnfcG4TDwSQHZrJHG/TqyFy9+4c6mJ0Y+ZLx7NPfoYmbPFnEKrqsPRWP/TAMpFIPpae76V+BM5M3GzteIbBwHuEsdFY79I6bZ034LcOkYH5N5Bjyf0nk1b5EK+ryYmTwFeBC1/7yVHAwsw8DwAXc+2Jj5/uF5/1vmjEfeNVEpQv+LUHyKyejtpsqhA4scCGRkIJgTHKsGMgUKpRHe/gp519eogwiWIf3X7JxAorMUbdLP162YBLM33su9HBlL7UyqMINsp1TJfe0GcmMs1CCVYonRBOm+vIhRRckxOj+EP5WWzhhoAffLRePb5eMEHfeQaUqE5xf4ncNfUo5Lbk82OH8kQPwyOjBR24SikbrTijXNgRkRHIP1t++02VPvgz9kGiLB7Jx5k+NDCAc2Okdp2gbweYlLxRmtKUQOJkFvKspmuC9cPecBzYDALqNsWB6lMlFV3eJLDc0HMelLtnDLn4ru+NjiDGw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
