travis:
  secure:
    BINSTAR_TOKEN: skgmM8TlnQmYDBqv122Dn3AB3zFfRQWL1l0DzCgB3vcOawLNtohvSye6PwmbSqU/1I0nP9KrlgAyUvloKBiogYFIb9g6jaErAJtqYwq7fkcG4kOD0TtpMI5BbsnikTSYcIBgAmMhYPo2pOpzVhRx5Vr3+sYuMHiDHunsfqMV2HOdaotaNX3c9Lh8Vn5KNXaAlm+GU0N/t+fxnfcG4TDwSQHZrJHG/TqyFy9+4c6mJ0Y+ZLx7NPfoYmbPFnEKrqsPRWP/TAMpFIPpae76V+BM5M3GzteIbBwHuEsdFY79I6bZ034LcOkYH5N5Bjyf0nk1b5EK+ryYmTwFeBC1/7yVHAwsw8DwAXc+2Jj5/uF5/1vmjEfeNVEpQv+LUHyKyejtpsqhA4scCGRkIJgTHKsGMgUKpRHe/gp519eogwiWIf3X7JxAorMUbdLP162YBLM33su9HBlL7UyqMINsp1TJfe0GcmMs1CCVYonRBOm+vIhRRckxOj+EP5WWzhhoAffLRePb5eMEHfeQaUqE5xf4ncNfUo5Lbk82OH8kQPwyOjBR24SikbrTijXNgRkRHIP1t++02VPvgz9kGiLB7Jx5k+NDCAc2Okdp2gbweYlLxRmtKUQOJkFvKspmuC9cPecBzYDALqNsWB6lMlFV3eJLDc0HMelLtnDLn4ru+NjiDGw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
