travis:
  secure:
    BINSTAR_TOKEN: xpcjBKF+spSqciRZgWxDnpQWZMvZQLpqVy94RzBS0BmuJdhBmMiUg4ykldWMaUPzHz6NXGW208B+GHzxoJAN8P5unbccOe1VT7hRHisRnS8aVkcjGstKVaZi06NKGkzFREoQCQ6mdNz8HxyOEpIB72WRBA6hdsBKVMMk5DapJSMWB0bf9JUierUjk8aC5s0SDW2U8okokBcSMRDgb0ADkbRJq3DIyer7id7oTsAHL+Hh+0TnHAgiVCee2PtZyjv+fQlXnbYhn3eM67kO6xrOIEkcx5UjZPwxe0EePSicfnmEbGmNwHDdCbk+aqe1nj5xP6+QL1BMSuOWXRvuPLcslLYHCI7GdfygWRhUfsiWR6zIQ7w19yTKfpfTd/ahSdaMaIFOjO24Qo7BKU079kSgVpgyVVWsovj8KhN1RfH2vVZgy2j8OJBwXhuP3ZRN2jCHOHRd1BD2rjj3/ERua6f2/jVlL/N6JIawXRUtgYTxYmM4bMmfX0mwzoBZ7XlDfccQEG/CGWCmLka6e6ufU2PYXi8o2GxN5E7V691lyRpnHGzdO6qRWb42DQ1H1mstOQkQqXP0NWOO/gBSzrFcXin+K7CoK5x7Id4UBOdPH3L9T741zW6z+jg/JCF0S+bzWgBNYQhD4jc2b4yOS7dO0AkLl7vPc0YfHxmtiQg9IJ8vDnc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
